### PR TITLE
Various Rock & Pebble UI Fixes

### LINKED ISSUE #33: Fix styling of rock, pebble, and pending pebble section left padding

### LINKED ISSUE #35: Don't display "Find Rocks" button when user has no rocks pending or otherwise

### LINKED ISSUE #36: Fix pending pebble section horizontal line at top below header to match others

### PR DESCRIPTION
**Pull request by DanielEFrampton**
### Sidebar Checklist

- [x] Request reviewers
- [x] Assign yourself and other contributors
- [x] Link to project

### Issues Resolved
Resolves #33, resolves #35, resolves #36 

### Problem Addressed
We found a number of small UI problems on the Rock & Pebble page.

### Solution Implemented
Fixed 'em.

### CODE REVIEW

File: src/containers/RockAndPebble/index.js [hunk 1]
```diff
@@ -108,8 +108,10 @@ const RockAndPebble = ({ user,
         </div>
           { pendingPebbles && pendingPebbles.length >= 1 && 
           <>
-            <div className='RockAndPebble--div'>        
-            <h2 className='RockAndPebble--header--h2'>Your Pending Pebble(s)</h2>
+            <div className='RockAndPebble--div'>
+              <div class="RockAndPebble--header--div">
```
Comment (rer7891) [inline src/containers/RockAndPebble/index.js:112]: Haha I swear that I had this header div here and couldn't get it to display the pebbles correctly. Glad it worked for you!

File: src/styles/_PebbleCard.scss [hunk 2]
```diff
@@ -17,8 +17,7 @@
   overflow: auto;
   height: 100%;
   width: 100%;
-  padding-left: 20px;
-  padding-bottom: 20px;
+  padding: 0px 20px 20px;
```
Comment (rer7891) [inline src/styles/_PebbleCard.scss:20]: Thanks for centering

**Review by rer7891 — APPROVED** [review]

File: src/containers/RockAndPebble/index.js (hunk 1 above)
Comment (DanielEFrampton) [reply src/containers/RockAndPebble/index.js:112]: I just had to ask nicely
